config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :products, only: :show
  resources :abouts, only: :index
  resources :categories, only: :show

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  get "orders/:cus_id&order_id=:order_id", to: "order#show", as: "order"
  get "orders/:cus_id", to: "order#index", as: "orders"
  post "order", to: "order#create", as: "order/create"
  post "cart/:id", to: "cart#create", as: "cart/create"
  delete "cart/:id&qty=:qty", to: "cart#destroy", as: "cart/destroy"
  get "search", to: "products#search", as: "search" # search_path
  get "about", to: "about#index", as: "about"

  root to: "categories#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, presence: true
  validates :model_year, numericality: { greater_than: 2010, only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  has_one_attached :product_image
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.find(1)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id].to_i
    session[:cart].push(id)
    redirect_to root_path
  end

  def destroy
    id = params[:id].to_i
    if params[:qty] == "1"
      session[:cart].delete_at(session[:cart].index(id) || session[:cart].length)
    else
      session[:cart].delete(id)
    end
    redirect_to root_path
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    order = Order.find(params[:order_id])

    if order.nil?
      redirect_to root_path
      nil
    end

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      line_items:           [{
        name:     "Total Price",
        amount:   (order.total_price * 100).to_i,
        currency: "cad",
        quantity: 1
      }],
      success_url:          checkout_success_url + "?session_id={CHECKOUT_SESSION_ID}" + "&order_id=#{order.id}",
      cancel_url:           checkout_cancel_url
    )

    respond_to do |format|
      format.js # render create.js.erb
    end
  end

  def success
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
    if @payment_intent["status"] == "succeeded"
      order = Order.find(params[:order_id])
      order.update(status: "paid", stripe_id: @payment_intent["id"])
    end

    session.delete("cart")
  end

  def cancel; end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  include Devise::Controllers::Helpers
  def create
    @current_cus = current_customer
    total = 0
    @products = []
    session[:cart].each do |i|
      product = Product.find(i)
      @products.push(product)
    end
    @products.each do |product|
      total += product.price
    end
    @province = Province.find_by(id: @current_cus.province_id)
    gst = total * @province.gst.to_d
    pst = total * @province.pst.to_d
    total += (total * @province.tax_rate)
    @order = Order.create(status: "new",
                          customer_id: @current_cus.id,
                          total_price: total, pst: pst, gst: gst)
    @products.each do |product|
      OrderItem.create(order_id: @order.id, product_id: product.id)
    end
  end

  def index
    @orders = Order.find_by(customer_id: params[:cus_id])
    @current_cus = Customer.find(params[:cus_id])
  end

  def show
    @order = Order.find(params[:order_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def search
    if params[:category] == "None"
      @products = Product.where("name LIKE ?", "%#{params[:search_term]}%")
    else
      @products = Product.where("name LIKE ? and category_id = #{params[:category]}", "%#{params[:search_term]}%")
    end
  end

  def filter
    sql = "sale_stat = Yes and created_at BETWEEN #{Time.zone.now.beginning_of_day..Time.zone.now.end_of_day}"
    sql1 = "sale_stat = Yes"
    sql2 = "created_at: #{Time.zone.now.beginning_of_day..Time.zone.now.end_of_day}"
    @products = if (params[:sale] == "1") && (params[:new] == "1")
                  Product.where(sql)
                elsif params[:sale] == "1"
                  Product.where(sql1)
                elsif params[:new] == "1"
                  Product.where(sql2)
                else
                  Product.all
                end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/order/_order.html.erb
<%if detail%>
  <h1>Order Details</h1>
  <h2>Order Number: <%= order.id%></h2>
  <ul>
      <% order.order_items.each do |i|%>
      <li><%= i.product.name%></li>
      <%end%>
  </ul>
  <p>PST: <%= order.gst%></p>
  <p>GST: <%= order.pst%></p>
  <p>Total: <%= order.total_price%></p>
<% else%>
  <tr>
    <td><%= link_to order.id, order_path(order.customer_id, order_id: order.id)%></td>
    <td><%= order.total_price%></td>
  </tr>
<%end%>

app/views/order/create.html.erb
<div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="top">
                <td colspan="2">
                    <table>
                        <tr>
                            <td class="title">
                                <img src="https://www.sparksuite.com/images/logo.png" style="width:100%; max-width:300px;">
                            </td>

                            <td>
                                Order #: <%= @order.id%><br>
                                Created: <%= @order.created_at%><br>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <tr class="information">
                <td colspan="2">
                    <table>
                        <tr>
                            <td>
                                <%= @province.name%><br>
                            </td>

                            <td>
                                <%= @current_cus.name %><br>
                                <%= @current_cus.email%>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>

            <tr class="heading">
                <td>
                    Item
                </td>

                <td>
                    Price
                </td>
            </tr>

            <% @products.each do |product|%>

            <tr class="item">
                <td>
                    <%= product.name%>
                </td>

                <td>
                    <% number_to_currency(product.price) %>
                </td>
            </tr>

            <%end%>

            <tr class="total">
                <td></td>

                <td>
                   GST: <%= number_to_currency(@order.gst)%><br>
                   PST: <%= number_to_currency(@order.pst)%><br>
                   Total: <%= number_to_currency(@order.total_price)%>
                </td>
            </tr>


        </table>
    <%= form_with url: checkout_create_path, remote: true do %>
      <%= hidden_field_tag(:order_id, @order.id, autocomplete: "off") %>
      <%= button_tag 'Buy Now' %>
    <% end %>
    </div>

app/views/order/index.html.erb
<h1><%= @current_cus.name%></h1>
<div>
  <table>
  <tr>
    <th>Order Number</th>
    <th>Total Price</th>
  </tr>
  <%= render partial: 'order/order', collection: @current_cus.orders, locals: {detail: false}%>
  </table>

</div>

app/views/order/show.html.erb
<div>
  <%= render partial: 'order', object: @order , locals: {detail: true}%>
</div>