config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :products, only: :show
  resources :abouts, only: :index
  resources :categories, only: :show

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "success", to: "checkout#success", as: "checkout_success"
  end

  get "orders/:cus_id&order_id=:order_id", to: "order#show", as: "order"
  get "orders/:cus_id", to: "order#index", as: "orders"
  post "order", to: "order#create", as: "order/create"
  post "cart/:id", to: "cart#create", as: "cart/create"
  delete "cart/:id&qty=:qty", to: "cart#destroy", as: "cart/destroy"
  get "search", to: "products#search", as: "search" # search_path
  get "about", to: "about#index", as: "about"

  root to: "categories#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  validates :name, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  has_many :products, through: :order_items
  belongs_to :customer
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, presence: true
  validates :model_year, numericality: { greater_than: 2010, only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  has_one_attached :product_image
end

app/models/province.rb
class Province < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @about = About.find(1)
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    id = params[:id].to_i
    session[:cart].push(id)
    redirect_to root_path
  end

  def destroy
    id = params[:id].to_i
    if params[:qty] == "1"
      session[:cart].delete_at(session[:cart].index(id) || session[:cart].length)
    else
      session[:cart].delete(id)
    end
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_item_helper.rb
module OrderItemHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

<% if customer_signed_in? %>
    <%= link_to "Log out", destroy_customer_session_path, :method=>'delete'%>
<% else %>
    <%= link_to "login", new_customer_session_path %>
<% end %>

<% if customer_signed_in? %>
<ul>
  <li><a href="/">All products</a></li>
  <li><%= link_to "Your Orders", orders_path(current_customer.id)%></li>
  <li><a href="/about">About</a></li>
</ul>
<%= debug session[:cart]%>
  Cart
   <ul>
          <li>
              <% if cart.present? %>
              <ul>
                <% cart.each do |product| %>
                  <li>
                    <%= product.name %>
                    <%= link_to '🡩', cart_create_path(product), method: :post %>
                    <%= link_to '🡣', cart_destroy_path(product, qty: "1"), method: :delete %>
                    <%= link_to '❌', cart_destroy_path(product, qty: "all"), method: :delete %>
                  </li>
                <% end %>
              </ul>
            <%=  link_to 'Checkout', order_create_path, method: :post%>
            <% end %>
          </li>
    </ul>
<%end%>

    <%= render partial: 'products/search', locals: {detail: false}%>
    <%= yield %>
</html>